name: Create Manifest JSON
on:
  push:
    branches: [ 'master' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Create Manifest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '20'
      - name: Update apt repo sources
        run: sudo apt-get update -y
      - name: Run jinxp
        run: |
          echo "*************************"
          wget --tries=5 --retry-connrefused --retry-on-host-error https://github.com/elanthia-online/jinxp/releases/download/v0.4.0/jinxp \
          && chmod +x jinxp \
          && ./jinxp -i scripts
          echo "*************************"
          ls dist/assets
          echo "*************************"
          ls dist/headers
          echo "*************************"
          ls dist
          echo "*************************"
          ls
          echo "*************************"
          cat dist/manifest.json
          echo "*************************"
